export const topics = [
  {
    id: 1,
    topic: "HTML",
    slug: "html5",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoDBNF5s-WH6aLbthSEIMhMI&si=Mc87ZQq4d_ju-Mom",
  },
  {
    id: 2,
    topic: "JavaScript",
    slug: "JavaScript",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoBuX3f4EOACle2y-tRC5Q37&si=-sEJi5wpaucdEZ5B",
  },
  {
    id: 3,
    topic: "ReactJs",
    slug: "React",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoDqgPchmvIsL4hTnJIrtige&si=25kpoBi1Z1JJ5UAr",
  },
  {
    id: 4,
    topic: "Flutter",
    slug: "Flutter",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoAtiwwVakdtUELcBNk5zvSJ&si=e7SxbeU5FV3RADvq",
  },
  {
    id: 5,
    topic: "React Native",
    slug: "React",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoAKL_sTfg5CgCxlrpH5b2jS&si=ds-J7KfFdZHJtW9D",
  },
  {
    id: 6,
    topic: "Express",
    slug: "express",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoBGh_8p_NS-ZAh6v7HhYqHW&si=qKgPKX-TKsft21te",
  },
  {
    id: 7,
    topic: "Python",
    slug: "python",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoBsMugTFALhdLlZ5VOqCg2s&si=7y_QhAcqskT-qPlv",
  },
  {
    id: 8,
    topic: "TailwindCSS",
    slug: "TailwindCSS",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoBLTxvkUIvy3_VR-vZK6Eq7&si=1PrCi6k65KKi3aDf",
  },
  {
    id: 9,
    topic: "NextJs",
    slug: "nextdotjs",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoDWGIwaEwhTUR40AbH8qsTo&si=3VdMzxHgOTJvQPDt",
  },
  {
    id: 10,
    topic: "django",
    slug: "django",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoDOf-6vAcKmazT92uLnWAgy&si=kx9l0yJ_J1qn5Yw_",
  },
  {
    id: 11,
    topic: "C++",
    slug: "C++",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoCPfgKZS8UE0MDuwiKvL8zi&si=IEl33lf8GBNl6MVd",
  },
  {
    id: 12,
    topic: "FastAPI",
    slug: "FastAPI",
    link: "https://youtube.com/playlist?list=PLu71SKxNbfoCFwFuOqIOG8iM1JeOLq3Wv&si=mfAYqWX1tVlsutJM",
  },
  {
    id: 13,
    topic: "NumPy",
    slug: "NumPy",
    link: "https://youtu.be/x7ULDYs4X84?si=Kvc8H9zLoAIOgo5T",
  },
  {
    id: 14,
    topic: "Git ",
    slug: "Git",
    link: "https://youtu.be/q8EevlEpQ2A?si=ANHmd5LLfPHhQFLR",
  },
  {
    id: 15,
    topic: "shadcn",
    slug: "shadcnui",
    link: "https://youtu.be/O4AjymzpIEg?si=kwkvtNeB6sRMkPD2",
  },
]